USE OnlineRetailDB;

-- Question 1: How many times has each customer made a purchase?
SELECT
    CustomerID,
    COUNT(DISTINCT InvoiceNo) AS TotalOrders
FROM OnlineRetail
GROUP BY CustomerID
ORDER BY TotalOrders DESC;

-- Question 2: What is the total revenue generated by each customer?
SELECT
    CustomerID,
    SUM(Revenue) AS TotalRevenue
FROM OnlineRetail
GROUP BY CustomerID
ORDER BY TotalRevenue DESC;

-- Question 3: How many days have passed since each customer's most recent purchase?
SELECT
    CustomerID,
    DATEDIFF(
        DAY,
        MAX(InvoiceDate),
        (SELECT MAX(InvoiceDate) FROM OnlineRetail)
    ) AS Recency
FROM OnlineRetail
GROUP BY CustomerID
ORDER BY Recency;

-- Question 4: What is the average purchase frequency per customer?
SELECT
    AVG(OrderCount) AS AvgFrequency
FROM (
    SELECT
        CustomerID,
        COUNT(DISTINCT InvoiceNo) AS OrderCount
    FROM OnlineRetail
    GROUP BY CustomerID
) AS CustomerFrequency;

-- Question 5: What is the average monetary value per customer?
SELECT
    AVG(TotalSpent) AS AvgMonetary
FROM (
    SELECT
        CustomerID,
        SUM(Revenue) AS TotalSpent
    FROM OnlineRetail
    GROUP BY CustomerID
) AS CustomerMonetary;

-- Question 6: How do you calculate the RFM score for each customer?
SELECT
    CustomerID,

    DATEDIFF(
        DAY,
        MAX(InvoiceDate),
        (SELECT MAX(InvoiceDate) FROM OnlineRetail)
    ) AS Recency,

    COUNT(DISTINCT InvoiceNo) AS Frequency,

    SUM(Revenue) AS Monetary

FROM OnlineRetail
GROUP BY CustomerID;

-- Question 7: Who are the top 10 customers with the highest Monetary value?
SELECT TOP 10
    CustomerID,
    SUM(Revenue) AS Monetary
FROM OnlineRetail
GROUP BY CustomerID
ORDER BY Monetary DESC;

-- Question 8: Which customer segment has low Recency and high Frequency?
WITH RFM AS (
    SELECT
        CustomerID,

        DATEDIFF(
            DAY,
            MAX(InvoiceDate),
            (SELECT MAX(InvoiceDate) FROM OnlineRetail)
        ) AS Recency,

        COUNT(DISTINCT InvoiceNo) AS Frequency

    FROM OnlineRetail
    GROUP BY CustomerID
)

SELECT *
FROM RFM
WHERE Recency <= 30
AND Frequency >= 10
ORDER BY Frequency DESC;

-- Question 9: How many customers belong to the "Loyal Customers" segment?
WITH RFM AS (
    SELECT
        CustomerID,

        DATEDIFF(
            DAY,
            MAX(InvoiceDate),
            (SELECT MAX(InvoiceDate) FROM OnlineRetail)
        ) AS Recency,

        COUNT(DISTINCT InvoiceNo) AS Frequency,

        SUM(Revenue) AS Monetary

    FROM OnlineRetail
    GROUP BY CustomerID
)

SELECT COUNT(*) AS LoyalCustomers
FROM RFM
WHERE Recency <= 30
AND Frequency >= 10
AND Monetary >= 5000;

-- Question 10: What is the distribution of customers across different RFM segments?
WITH RFM AS (
    SELECT
        CustomerID,

        DATEDIFF(
            DAY,
            MAX(InvoiceDate),
            (SELECT MAX(InvoiceDate) FROM OnlineRetail)
        ) AS Recency,

        COUNT(DISTINCT InvoiceNo) AS Frequency,

        SUM(Revenue) AS Monetary

    FROM OnlineRetail
    GROUP BY CustomerID
)

SELECT
    CASE
        WHEN Recency <= 30 AND Frequency >= 10 THEN 'Loyal'
        WHEN Recency <= 90 AND Frequency >= 5 THEN 'Potential Loyalist'
        ELSE 'Others'
    END AS Segment,

    COUNT(*) AS TotalCustomers

FROM RFM
GROUP BY
    CASE
        WHEN Recency <= 30 AND Frequency >= 10 THEN 'Loyal'
        WHEN Recency <= 90 AND Frequency >= 5 THEN 'Potential Loyalist'
        ELSE 'Others'
    END;